# Features mostly same as in the following paper:
# Jain, S. and Thiagarajan, B. and Shi, Z. and Clabaugh, C. and Mataric, M. J.,
# "Modeling engagement in long-term, in-home socially assistive robot interventions
#  for children with autism spectrum disorders," Science Robotics, vol. 5, no. 39, 2020.

float64 pitch_frequency
float64 var_pitch_frequency

float64 pitch_strength
float64 var_pitch_strength

float64 mean_harmonicity
float64 var_harmonicity

float64 mean_intensity
float64 var_intensity

# Mel-frequency cepstral coefficients
float64[] mfccs
float64[] var_mfccs
