# Features mostly same as in the following paper:
# Jain, S. and Thiagarajan, B. and Shi, Z. and Clabaugh, C. and Mataric, M. J.,
# "Modeling engagement in long-term, in-home socially assistive robot interventions
#  for children with autism spectrum disorders," Science Robotics, vol. 5, no. 39, 2020.

# Mel-frequency cepstral coefficients
float64[] mfccs

float64 intensity
float64 pitch_frequency
float64 periodicity
